export interface ChangeSection {
  id: string;
  groupId: string;
  before: readonly [startLine: number, endLine: number];
  after: readonly [startLine: number, endLine: number];
  reason: string;
}

export const groups = [
  { id: "intro", title: "보고서 도입" },
  { id: "summary", title: "0. 요약" },
  { id: "definitions", title: "1. 용어 정의" },
  { id: "approach", title: "2. 단계적 접근 전략" },
  { id: "injection", title: "3. DI와 IoC" },
  { id: "extension", title: "4. OCP" },
  { id: "environments", title: "5. 실행 환경" },
  { id: "performance", title: "6. 성능과 렌더링" },
  { id: "pitfalls", title: "7. 안티패턴" },
  { id: "selection", title: "8. 환경과 전달 방식" },
  { id: "conditions", title: "9. 적용 조건" },
  { id: "sources", title: "10. 출처" },
  { id: "limits", title: "11. 적용 환경별 확인 사항" },
] as const;

export const changeSections = [
  {
    id: "change-1",
    groupId: "intro",
    before: [2, 11],
    after: [2, 7],
    reason: "표현 수정: 작성 과정 설명과 중복 부제를 덜고 보고서의 결론을 먼저 제시했습니다.",
  },
  {
    id: "change-2",
    groupId: "summary",
    before: [15, 22],
    after: [11, 18],
    reason: "기술 설명 보정: DI와 OCP의 한 가지 구성을 표준이나 무수정 확장으로 단정하지 않고 적용 조건을 밝혔습니다.",
  },
  {
    id: "change-3",
    groupId: "definitions",
    before: [30, 34],
    after: [26, 30],
    reason: "기술 설명 보정: DI, OCP와 Server Component의 정의에 실제로 가능한 동작을 반영했습니다.",
  },
  {
    id: "change-4",
    groupId: "approach",
    before: [42, 45],
    after: [38, 41],
    reason: "표현 수정: 추상적인 단계 설명 대신 React 문서의 권고와 이 보고서의 제안을 구별했습니다.",
  },
  {
    id: "change-5",
    groupId: "approach",
    before: [49, 50],
    after: [45, 46],
    reason: "표현 수정: 중간 컴포넌트가 전달하는 값과 불필요한 전달 단계를 직접 적었습니다.",
  },
  {
    id: "change-6",
    groupId: "approach",
    before: [54, 54],
    after: [50, 50],
    reason: "표현 수정: Context 값을 제공하는 컴포넌트와 읽는 컴포넌트를 구분했습니다.",
  },
  {
    id: "change-7",
    groupId: "approach",
    before: [59, 60],
    after: [55, 56],
    reason: "기술 설명 보정: DI 컨테이너와 외부 스토어를 검토할 조건이 서로 다름을 밝혔습니다.",
  },
  {
    id: "change-8",
    groupId: "injection",
    before: [67, 67],
    after: [63, 63],
    reason: "표현 수정: 예시 작성 과정을 설명하는 문장을 덜고 코드의 문법과 적용 조건을 설명했습니다.",
  },
  {
    id: "change-9",
    groupId: "injection",
    before: [81, 81],
    after: [77, 77],
    reason: "예시 교정: Provider 누락 오류 메시지에서 이름과 Provider 사이의 공백을 바로잡았습니다.",
  },
  {
    id: "change-10",
    groupId: "injection",
    before: [96, 96],
    after: [92, 92],
    reason: "표현 수정: 인터페이스를 도메인이 관리한다고 단정한 주석 대신 그 인터페이스를 쓰는 코드를 적었습니다.",
  },
  {
    id: "change-11",
    groupId: "injection",
    before: [128, 129],
    after: [124, 125],
    reason: "기술 설명 보정: Context 기반 의존성 전달을 React가 정한 표준 DI 형식으로 소개하지 않도록 고쳤습니다.",
  },
  {
    id: "change-12",
    groupId: "injection",
    before: [142, 142],
    after: [138, 138],
    reason: "표현 수정: 의존성 객체가 유지되는 기간을 Provider 인스턴스에 맞춰 설명했습니다.",
  },
  {
    id: "change-13",
    groupId: "injection",
    before: [151, 152],
    after: [147, 148],
    reason: "기술 설명 보정: 서버 렌더링 중 브라우저 API에 접근하면 실패하는 조건을 구체화했습니다.",
  },
  {
    id: "change-14",
    groupId: "injection",
    before: [156, 157],
    after: [152, 157],
    reason: "예시 교정: 테스트에서 Provider와 QueryClient를 어떻게 마련하는지 설명하고 빠진 import를 채웠습니다.",
  },
  {
    id: "change-15",
    groupId: "injection",
    before: [161, 176],
    after: [161, 177],
    reason: "예시 교정: 테스트마다 QueryClient를 만들고 게시물의 실제 내용을 확인하도록 바꿨습니다.",
  },
  {
    id: "change-16",
    groupId: "injection",
    before: [182, 185],
    after: [183, 186],
    reason: "기술 설명 보정: 커뮤니티 라이브러리의 유지보수와 React 19 호환성을 확인하지 않은 채 평가하지 않도록 고쳤습니다.",
  },
  {
    id: "change-17",
    groupId: "extension",
    before: [191, 191],
    after: [192, 192],
    reason: "표현 수정: 슬롯이 유지하는 부분과 바꾸는 부분을 제목에서 구별했습니다.",
  },
  {
    id: "change-18",
    groupId: "extension",
    before: [195, 198],
    after: [196, 199],
    reason: "기술 설명 보정: Radix의 모든 구성 요소가 아닌 asChild를 제공하는 구성 요소에만 설명을 적용했습니다.",
  },
  {
    id: "change-19",
    groupId: "extension",
    before: [202, 218],
    after: [203, 226],
    reason: "기술 설명 및 예시 교정: Provider 교체에도 조립 코드는 수정됨을 밝히고 렌더러 예시의 any를 없앴습니다.",
  },
  {
    id: "change-20",
    groupId: "extension",
    before: [222, 229],
    after: [230, 234],
    reason: "표현 수정: 렌더러 등록표에서 수정해야 하는 위치와 실행 환경별 설명을 구체화했습니다.",
  },
  {
    id: "change-21",
    groupId: "environments",
    before: [233, 238],
    after: [238, 243],
    reason: "기술 설명 보정: 환경 비교표에 React 19.3의 Context 렌더링과 서버 값 전달 조건을 반영했습니다.",
  },
  {
    id: "change-22",
    groupId: "environments",
    before: [242, 244],
    after: [247, 249],
    reason: "기술 설명 보정: 클라이언트 전용 앱에 아무런 제약도 없다는 단정을 줄였습니다.",
  },
  {
    id: "change-23",
    groupId: "environments",
    before: [248, 259],
    after: [253, 262],
    reason: "기술 설명 보정: Server Component의 Context 생성 및 읽기 제한과 React 19.3의 렌더링 허용을 구분했습니다.",
  },
  {
    id: "change-24",
    groupId: "environments",
    before: [281, 281],
    after: [284, 284],
    reason: "표현 수정: Promise 값을 읽는 Client Component와 Suspense의 관계를 주석에 명시했습니다.",
  },
  {
    id: "change-25",
    groupId: "environments",
    before: [286, 287],
    after: [289, 290],
    reason: "기술 설명 보정: Promise를 다시 가져올 때 갱신해야 하는 Server Component의 위치를 밝혔습니다.",
  },
  {
    id: "change-26",
    groupId: "environments",
    before: [293, 296],
    after: [296, 298],
    reason: "기술 설명 보정: React.cache의 요청 중 재사용과 의존성 주입을 서로 다른 역할로 설명했습니다.",
  },
  {
    id: "change-27",
    groupId: "environments",
    before: [300, 300],
    after: [302, 302],
    reason: "기술 설명 보정: 서버 QueryClient 생성과 브라우저 재사용 방식을 공식 예시에 맞춰 적었습니다.",
  },
  {
    id: "change-28",
    groupId: "environments",
    before: [305, 308],
    after: [307, 310],
    reason: "기술 설명 보정: React Router의 두 Context API를 구분하고 v7 middleware 설정 조건을 밝혔습니다.",
  },
  {
    id: "change-29",
    groupId: "environments",
    before: [312, 312],
    after: [314, 314],
    reason: "기술 설명 보정: Expo Router에서 의존성을 제공할 위치는 확인되지 않았음을 명시했습니다.",
  },
  {
    id: "change-30",
    groupId: "performance",
    before: [318, 322],
    after: [320, 324],
    reason: "기술 설명 보정: Context 변경의 영향을 받는 컴포넌트와 Compiler 최적화의 확인 조건을 구체화했습니다.",
  },
  {
    id: "change-31",
    groupId: "pitfalls",
    before: [328, 335],
    after: [330, 337],
    reason: "기술 설명 보정: Provider 누락, 값 직렬화와 추상화에 관한 주의사항의 적용 조건을 밝혔습니다.",
  },
  {
    id: "change-32",
    groupId: "selection",
    before: [339, 349],
    after: [341, 347],
    reason: "표현 수정: 일률적인 선택 지시 대신 필요한 값과 실행 환경에 따라 검토할 순서를 적었습니다.",
  },
  {
    id: "change-33",
    groupId: "conditions",
    before: [353, 361],
    after: [351, 359],
    reason: "기술 설명 보정: 특정 파일 배치와 모든 Context 훅의 예외 처리를 필수 규칙으로 제시하지 않도록 고쳤습니다.",
  },
  {
    id: "change-34",
    groupId: "sources",
    before: [375, 380],
    after: [373, 381],
    reason: "기술 설명 보정: React 19.3과 React Router 공식 출처를 보태고 확인되지 않은 Next.js 문서 버전을 지웠습니다.",
  },
  {
    id: "change-35",
    groupId: "limits",
    before: [401, 413],
    after: [402, 408],
    reason: "기술 설명 보정: 이미 확인한 항목을 추가 과제에서 제외하고 실제 적용 버전에 따라 달라지는 항목을 남겼습니다.",
  },
] as const satisfies readonly ChangeSection[];
